### PR TITLE
Api documentation

### PR DESCRIPTION
**Pull request by anupam-git**
Here is a basic documentation for P2PT.
We were discussing about this in issue #2.

### CODE REVIEW

**Comment by subins2000** [comment]
Can you please make this a separate file ? `api-docs.md`

**Comment by anupam-git** [comment]
> Can you please make this a separate file ? `api-docs.md`

done..

**Comment by subins2000** [comment]
Thank you for your contribution @anupam-git :)

**Comment by anupam-git** [comment]
:+1:

**Pull request merged**
