### PR TITLE
fix: modernise

### PR DESCRIPTION
**Pull request by ThaUnknown**
modernises this package to use ESM and latest versions of it's dependencies

by updating bittorrent-tracker drops the need to import/polyfill buffer, readable-stream, inherits, string_decoder and a few others

### CODE REVIEW

**Comment by subins2000** [comment]
Just checked this out, good work! Thanks! Please assign to me when it's ready

**Comment by ThaUnknown** [comment]
> Just checked this out, good work! Thanks! Please assign to me when it's ready

it is ready as it isnt a draft, I dont have permissions to assign people as im not part of the repo

**Comment by ThaUnknown** [comment]
@subins2000

**Comment by ThaUnknown** [comment]
\o/

**Comment by ThaUnknown** [comment]
@subins2000 you never published this to npm xD

**Comment by kemo-1** [comment]
such a great library i wonder why i can't connect to web trackers but i can use https://github.com/webtorrent/webtorrent ??

**Comment by kemo-1** [comment]
nvm i finnaly got it working

import 'https://unpkg.com/@leofcoin/p2pt@1.7.7/exports/browser/p2pt.umd.js'

export async function init_connection() {
  const trackersAnnounceURLs = [
    "wss://tracker.openwebtorrent.com"
  ]

  // The second argument is an identifier for your app/room
  const p2pt = new P2PT(trackersAnnounceURLs, 'my-app-id')

  // Start the P2PT instance
  await p2pt.start()

  // Optional: log when a tracker connects
  p2pt.on("trackerconnect", (tracker) => {
    console.log("Connected to tracker:", tracker.announceUrl)
  })

  p2pt.on("trackerwarning", (err) => {
    console.warn("Tracker warning:", err)
  })

  // You can also listen for peer events:
  p2pt.on("peerconnect", (peer) => {
    console.log("Connected to peer:", peer.id)
  })

  p2pt.on("peerclose", (peer) => {
    console.log("Peer disconnected:", peer.id)
  })
}

**Pull request merged**
